# Generated by Django 3.1.8 on 2021-06-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='back',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='card',
            name='front',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='stack',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
