# Generated by Django 3.1.8 on 2021-06-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
        ('flashcards', '0002_auto_20210604_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='stack',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stacks.stack'),
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
