# Generated by Django 3.1.8 on 2021-06-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
        ('flashcards', '0003_auto_20210604_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stacks.stack'),
            preserve_default=False,
        ),
    ]
